[package]
name = "rustfulapi"
authors = ["Mahdi Robatipoor<mahdi.robatipoor@gmail.com>"]
description = "RESTful API template built with Rust language"
edition = "2021"
homepage = "https://github.com/robatipoor/rustfulapi"
keywords = ["web", "api", "rest","orm"]
license = "MIT"
repository = "https://github.com/robatipoor/rustfulapi"
version = "0.1.0"

[[bin]]
name = "app"
path = "./src/bin/app.rs"

[[bin]]
name = "migration"
path = "./src/bin/migration.rs"

[dependencies]
axum = { version = "0.7.5", features = ["ws"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
sea-orm = { version = "0.12.15", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
sea-orm-migration = { version = "0.12.15", features = [
  "runtime-tokio-rustls",
  "sqlx-postgres",
] }
anyhow = "1.0.81"
argon2 = "0.5.3"
async-trait = "0.1.77"
base64 = "0.22.0"
chrono = { version = "0.4.37", default-features = false, features = [
  "clock",
  "serde",
] }
config = "0.14.0"
fake = { version = "2.9.2", features = ["derive", "uuid", "chrono"] }
futures = "0.3.30"
itertools = "0.12.1"
jsonwebtoken = "9.3.0"
lettre = { version = "0.11.6", features = ["tokio1-native-tls", "builder"] }
log = "0.4.21"
log-derive = "0.4.1"
once_cell = "1.19.0"
openssl = "0.10.64"
rand = "0.8.5"
rand_core = { version = "0.6.4", features = ["std"] }
redis = { version = "0.25.2", features = ["tokio-comp"] }
reqwest = { version = "0.12.2", features = ["json", "multipart", "stream"] }
scraper = "0.19.0"
sentry = "0.32.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
sha2 = "0.10.8"
strum = { version = "0.26.2", features = ["derive"] }
tera = "1.19.1"
test-context = "0.3.0"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-appender = "0.2.3"
tracing-bunyan-formatter = "0.3.9"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = [
  "registry",
  "env-filter",
] }
url = "2.5.0"
utoipa = { version = "4.2.0", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
tokio-tungstenite = "0.21.0"
garde = { version = "0.18.0", features = ["full"] }
regex = "1.10.4"
wiremock = "0.6.0"