[package]
name = "rustfulapi"
authors = ["Mahdi Robatipoor<mahdi.robatipoor@gmail.com>"]
description = "RESTful API template built with Rust language"
edition = "2021"
homepage = "https://github.com/robatipoor/rustfulapi"
keywords = ["web", "api", "rest","orm"]
license = "MIT"
repository = "https://github.com/robatipoor/rustfulapi"
version = "0.1.0"

[[bin]]
name = "app"
path = "./src/bin/app.rs"

[[bin]]
name = "migration"
path = "./src/bin/migration.rs"

[dependencies]
axum = { version = "0.7.1", features = ["ws"] }
axum-extra = { version = "0.9.0", features = ["typed-header"] }
sea-orm = { version = "0.12.7", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
sea-orm-migration = { version = "0.12.6", features = [
  "runtime-tokio-rustls",
  "sqlx-postgres",
] }
anyhow = "1.0.75"
argon2 = "0.5.2"
async-trait = "0.1.74"
base64 = "0.21.5"
chrono = { version = "0.4.31", default-features = false, features = [
  "clock",
  "serde",
] }
config = "0.13.4"
derive_more = "0.99.17"
fake = { version = "2.9.1", features = ["derive", "uuid", "chrono"] }
futures = "0.3.29"
hex = "0.4.3"
hex-literal = "0.4.1"
hmac = "0.12.1"
itertools = "0.12.0"
jsonwebtoken = "9.2.0"
lettre = { version = "0.11.2", features = ["tokio1-native-tls", "builder"] }
log = "0.4.20"
log-derive = "0.4.1"
mockall = "0.12.0"
once_cell = "1.18.0"
openssl = "0.10.60"
project-root = "0.2.2"
rand = "0.8.5"
rand_core = { version = "0.6.4", features = ["std"] }
redis = { version = "0.24.0", features = ["tokio-comp"] }
reqwest = { version = "0.11.22", features = ["json", "multipart", "stream"] }
sanitize-filename = "0.5.0"
scraper = "0.18.1"
sentry = "0.32.0"
sentry-actix = "0.32.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sha2 = "0.10.8"
strum = { version = "0.25.0", features = ["derive"] }
tempfile = "3.8.1"
tera = "1.19.1"
test-context = "0.1.4"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-actix-web = "0.7.9"
tracing-appender = "0.2.3"
tracing-bunyan-formatter = "0.3.9"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = [
  "registry",
  "env-filter",
] }
url = "2.5.0"
utoipa = { version = "4.1.0", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "5.0.0", features = ["axum"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
tokio-tungstenite = "0.21.0"
wiremock = "0.5.22"
garde = "0.16.3"
regex = "1.10.2"
