name: clippy check
on:
  push:
    branches: ["main","develop"]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  clippy:
    name: Cargo clippy
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features

