name: spell checker
on: [pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
  
      - name: Check spelling
        uses: crate-ci/typos@master
